library(tidyverse)
library(sf)
library(rnaturalearth)
library(ggplot2)

world <- rnaturalearth::ne_countries(returnclass = "sf")

## Dataverse
# Download dataverse json
dataverse_json_url <- "https://services.dataverse.harvard.edu/miniverse/map/installations-json/pretty"
dir.create("node_locations")
dataverse_fn <- "node_locations/dataverse.json"
download.file(dataverse_json_url, dataverse_fn)

# as downloaded, there are some html tags that need to be removed
d <- readr::read_lines(dataverse_fn) %>%
    stringr::str_replace_all("<.*?>", "")
d %>% readr::write_lines(dataverse_fn)

# read json and convert to sf
dataverse <- jsonlite::fromJSON(dataverse_fn)[[1]] %>%
    sf::st_as_sf(
        coords = c('lng', 'lat'),
        crs = "+init=epsg:4326"
    )

## GBIF
# I'm in a hurry and sort of guessing at some of this, but I think
# there are 1,733 publishers [according to this](https://www.gbif.org/publisher/search).
# The [api summary](https://www.gbif.org/developer/summary) says there's
# a limit of the records delivered in one query. It doesn't seem to
# explicitly state what the limit is, but trial and error indicates
# it's 1000. So I'll have to do 2 queries to get all the records.
gbif_url1 <- "https://www.gbif.org/api/publisher/search?isEndorsed=true&locale=en&format=json&offset=0&limit=1000"
gbif_url2 <- "https://www.gbif.org/api/publisher/search?isEndorsed=true&locale=en&format=json&offset=1000&limit=1000"
gbif_fns <- paste0("node_locations/gbif", c("1", "2"), ".json")
download.file(gbif_url1, gbif_fns[1])
download.file(gbif_url2, gbif_fns[2])
gbif1 <- jsonlite::fromJSON(gbif_fns[1])[['results']] %>%
    select('latitude', 'longitude', 'title', 'country', 'abbreviation')
gbif2 <- jsonlite::fromJSON(gbif_fns[2])[['results']] %>%
    select('latitude', 'longitude', 'title', 'country', 'abbreviation')
gbif <- bind_rows(gbif1, gbif2) %>%
    filter(complete.cases(latitude, longitude))%>%
    sf::st_as_sf(
        coords = c('longitude', 'latitude'),
        crs = "+init=epsg:4326"
    )

## DataOne
# These points come from the csv generated by `dataone-nodes.sh`
# run `dataone-nodes.sh` to refresh the file
dataone <- read.csv("dataone-nodes.csv") %>%
    mutate(name=stringi::stri_sub(name,10)) %>%
    sf::st_as_sf(
        coords = c('lon', 'lat'),
        crs = "+init=epsg:4326"
    )

## Combine networks into on sf data.frame (or whatever its called)
# sflist <- list(
#     gbif=gbif %>%
#         select(geometry) %>%
#         mutate(Network="GBIF"),
#     dataone=dataone %>%
#         select(geometry) %>%
#         mutate(Network="DataOne"),
#     dataverse=dataverse %>%
#         select(geometry) %>%
#         mutate(Network="Dataverse")
# )

gbif_sf <- gbif %>%
    select(geometry) %>%
    mutate(Network="GBIF")

dataverse_sf <- dataverse %>%
    select(geometry) %>%
    mutate(Network="Dataverse")

dataone_sf <- dataone %>%
    select(geometry) %>%
    mutate(Network="DataOne")

# nodes <- do.call(rbind, sflist) %>%
#     arrange(Network)


m <- ggplot() +
    geom_sf(data=world, color=NA, fill="gray90") +
    geom_sf(data=gbif_sf,
            mapping=aes(color=Network, alpha=Network), size=2,
            show.legend = "point") +
    geom_sf(data=dataverse_sf, mapping=aes(color=Network), size=2.5, alpha=0.75, show.legend = "point") +
    geom_sf(data=dataone_sf, mapping=aes(color=Network), size=2.5, alpha=0.75, show.legend = "point") +
    scale_alpha_manual(guide='none', values = list(GBIF = 0.5, DataOne = 0.5, Dataverse=0.5)) +
    theme(#panel.grid.major = element_line(colour = 'transparent'),
            # axis.title.x=element_blank(),
            axis.text.x=element_blank(),
            axis.ticks.x=element_blank(),
            axis.title.y=element_blank(),
            axis.text.y=element_blank(),
            axis.ticks.y=element_blank(),
            panel.background=element_rect(fill="white"),
            legend.position = c(.2, .05),
            legend.justification = c("left", "bottom"),
            legend.direction = "horizontal"
            #legend.position = "bottom"
            # panel.border=element_blank(),
            # panel.grid.minor=element_blank(),
            # plot.background=element_blank()
        )

m

out_fn = "network_map.png"
ggsave(out_fn, plot=m, dpi="print", width=5, height=3)
